spring:
  application:
    name: JuryScan-API-prod
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Only validate the db schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false

api:
  uri: /api/v1