spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${H2_USER:test}
    password: ${H2_PASSWORD:test}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false