spring:
  application:
    name: JuryScan-API-prod
  datasource:
    url: ${PG_URL}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # Only validate the db schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false

api:
  uri: /api/v1
  data-load:
    create-default-users: ${CREATE_DEFAULT_USERS:false}
    create-dump-data: ${CREATE_DUMP_DATA:false}
  security:
    token:
      secret: ${JWT_SECRET}